version: '2'
services:
  jupyter:
    image: jupy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # - ".:/home/jupy/notebooks"
      - ".:/notebooks"
